CREATE TABLE [dbo].[user] (
	[USER_ID] INT IDENTITY(1,1) NOT NULL,
	[FULL_NAME] NVARCHAR(100) NOT NULL,
	[EMAIL] NVARCHAR(100) NOT NULL,
	[USERNAME] NVARCHAR(20) NOT NULL,
	[PASSWORD] NVARCHAR(64) NOT NULL
	PRIMARY KEY CLUSTERED ([USER_ID] ASC)
	)